### ISSUE TITLE
Which part of your code use ligsite to detect binding site?

### ISSUE THREAD

**Issue by ludlows** [avkitex/pdbparserTools#1]
Hi avkitex,
    I want to learn to detect binding site from your code. 
But I have no clues right now. Could you please give me a hint?

Thanks,
ludlows

**Comment by avkitex** [comment]
Sorry for late response.
Here you can find custom Ligsite realization for known binding site atoms detection.
You already have to know it's actual center and average size. 
Try getProteinActiveSiteAtoms, getProteinContactsAsBitVectors from clusterMols/clusterize.py
Protein atoms are organized as vector. Algorithm will rate up atoms with are likely to be on the surface.


Take a look at https://github.com/avkitex/pdbparserTools/blob/master/clusterMols/getResults.py#L295
